-- 027_daily_affirmations.sql
-- 365 affirmations — une par jour (brief Shy « Module Mindset », v2.0, sept. 2026).
-- La phrase dépend de la date LOCALE de l'appareil (mois + jour), pas de la date
-- d'inscription : toutes les utilisatrices lisent la même phrase le même jour.
-- Le 29 février porte l'affirmation bonus ; les autres jours ne sont pas décalés.
-- Volontairement : aucun compteur, aucun historique, aucune donnée par utilisatrice.
-- Texte de référence = français (apostrophes ’ et guillemets « » conservés) ;
-- i18n.en.text = version anglaise. Les autres langues retombent sur le français.

create table if not exists public.daily_affirmations (
  month smallint not null check (month between 1 and 12),
  day smallint not null check (day between 1 and 31),
  text text not null,
  i18n jsonb default '{}'::jsonb,
  updated_at timestamptz default now(),
  primary key (month, day)
);

alter table public.daily_affirmations enable row level security;

drop policy if exists "daily_affirmations_read" on public.daily_affirmations;
create policy "daily_affirmations_read" on public.daily_affirmations
  for select to authenticated using (true);
drop policy if exists "daily_affirmations_admin_write" on public.daily_affirmations;
create policy "daily_affirmations_admin_write" on public.daily_affirmations
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.daily_affirmations (month, day, text, i18n) values
  (1, 1, 'Cette année, je choisis de me faire confiance.', '{"en": {"text": "This year, I choose to trust myself."}}'::jsonb),
  (1, 2, 'Je n’attends pas le bon moment : je le crée.', '{"en": {"text": "I don’t wait for the right moment: I create it."}}'::jsonb),
  (1, 3, 'Chaque petit geste d’aujourd’hui construit la femme de demain.', '{"en": {"text": "Every small step today builds the woman I’ll be tomorrow."}}'::jsonb),
  (1, 4, 'J’avance à mon rythme, et j’avance vraiment.', '{"en": {"text": "I move at my own pace, and I truly move forward."}}'::jsonb),
  (1, 5, 'Je suis capable de changer ce qui compte pour moi.', '{"en": {"text": "I am capable of changing what matters to me."}}'::jsonb),
  (1, 6, 'Aujourd’hui, je fais un pas. Demain, un autre.', '{"en": {"text": "Today, I take one step. Tomorrow, another."}}'::jsonb),
  (1, 7, 'Mon énergie grandit chaque fois que je tiens parole envers moi.', '{"en": {"text": "My energy grows every time I keep my word to myself."}}'::jsonb),
  (1, 8, 'Je commence là où je suis, avec ce que j’ai.', '{"en": {"text": "I start where I am, with what I have."}}'::jsonb),
  (1, 9, 'Mon corps est prêt à me suivre ; je lui fais confiance.', '{"en": {"text": "My body is ready to follow me; I trust it."}}'::jsonb),
  (1, 10, 'Je transforme mes intentions en gestes concrets.', '{"en": {"text": "I turn my intentions into real actions."}}'::jsonb),
  (1, 11, 'La régularité est ma force secrète.', '{"en": {"text": "Consistency is my secret strength."}}'::jsonb),
  (1, 12, 'Je suis l’autrice de mon année.', '{"en": {"text": "I am the author of my year."}}'::jsonb),
  (1, 13, 'Chaque matin, je choisis d’être de mon côté.', '{"en": {"text": "Every morning, I choose to be on my own side."}}'::jsonb),
  (1, 14, 'Je me lève avec l’envie de prendre soin de moi.', '{"en": {"text": "I wake up wanting to take care of myself."}}'::jsonb),
  (1, 15, 'Recommencer, c’est déjà avancer.', '{"en": {"text": "Starting again is already moving forward."}}'::jsonb),
  (1, 16, 'Je construis quelque chose de solide, jour après jour.', '{"en": {"text": "I am building something solid, day after day."}}'::jsonb),
  (1, 17, 'Même en hiver, je garde mon feu intérieur allumé.', '{"en": {"text": "Even in winter, I keep my inner fire burning."}}'::jsonb),
  (1, 18, 'Mes envies sont plus fortes que mes hésitations.', '{"en": {"text": "My desires are stronger than my hesitations."}}'::jsonb),
  (1, 19, 'Je crée des rituels qui me donnent de l’élan.', '{"en": {"text": "I create rituals that give me momentum."}}'::jsonb),
  (1, 20, 'Je suis déjà en chemin, et ce chemin me plaît.', '{"en": {"text": "I am already on my way, and I like this path."}}'::jsonb),
  (1, 21, 'Un jour sans séance ne m’arrête pas : je reprends demain.', '{"en": {"text": "A day without a session doesn’t stop me: I pick it up tomorrow."}}'::jsonb),
  (1, 22, 'Je sais ce dont j’ai besoin, et je me l’offre.', '{"en": {"text": "I know what I need, and I give it to myself."}}'::jsonb),
  (1, 23, 'Prendre soin de moi est une priorité, pas une option.', '{"en": {"text": "Taking care of myself is a priority, not an option."}}'::jsonb),
  (1, 24, 'La discipline douce me mène loin.', '{"en": {"text": "Gentle discipline takes me far."}}'::jsonb),
  (1, 25, 'Je dis « je choisis », et je passe à l’action.', '{"en": {"text": "I say “I choose”, and I take action."}}'::jsonb),
  (1, 26, 'Je suis fière de chaque pas, même le plus petit.', '{"en": {"text": "I am proud of every step, even the smallest."}}'::jsonb),
  (1, 27, 'Mon année se construit un jour à la fois, et aujourd’hui compte.', '{"en": {"text": "My year is built one day at a time, and today matters."}}'::jsonb),
  (1, 28, 'Je garde ce qui me porte, et j’avance.', '{"en": {"text": "I keep what lifts me, and I move forward."}}'::jsonb),
  (1, 29, 'C’est moi qui décide de la direction.', '{"en": {"text": "I am the one who decides the direction."}}'::jsonb),
  (1, 30, 'Chaque effort que je fais pour moi porte ses fruits.', '{"en": {"text": "Every effort I make for myself bears fruit."}}'::jsonb),
  (1, 31, 'Je termine ce mois plus forte qu’au premier jour.', '{"en": {"text": "I end this month stronger than on its first day."}}'::jsonb),
  (2, 1, 'Je me parle comme une coach qui croit en moi.', '{"en": {"text": "I talk to myself like a coach who believes in me."}}'::jsonb),
  (2, 2, 'Ma douceur est une force.', '{"en": {"text": "My gentleness is a strength."}}'::jsonb),
  (2, 3, 'Je suis ma meilleure alliée.', '{"en": {"text": "I am my own best ally."}}'::jsonb),
  (2, 4, 'Mes imperfections ne m’empêchent pas d’avancer.', '{"en": {"text": "My imperfections don’t stop me from moving forward."}}'::jsonb),
  (2, 5, 'Je grandis sans me renier.', '{"en": {"text": "I grow without betraying who I am."}}'::jsonb),
  (2, 6, 'Je n’ai pas besoin d’être parfaite pour être formidable.', '{"en": {"text": "I don’t need to be perfect to be wonderful."}}'::jsonb),
  (2, 7, 'Les jours difficiles me rendent plus solide.', '{"en": {"text": "Hard days make me more solid."}}'::jsonb),
  (2, 8, 'Je respecte mon corps, et il me le rend.', '{"en": {"text": "I respect my body, and it gives back."}}'::jsonb),
  (2, 9, 'Je regarde mon reflet avec fierté.', '{"en": {"text": "I look at my reflection with pride."}}'::jsonb),
  (2, 10, 'Je ralentis quand il le faut, pour mieux repartir.', '{"en": {"text": "I slow down when I need to, so I can set off again."}}'::jsonb),
  (2, 11, 'Ma valeur est immense, et elle ne se mesure pas.', '{"en": {"text": "My worth is immense, and it cannot be measured."}}'::jsonb),
  (2, 12, 'Je suis assez, et j’ai encore tant à découvrir.', '{"en": {"text": "I am enough, and I still have so much to discover."}}'::jsonb),
  (2, 13, 'Mon corps accomplit des merveilles chaque jour, et je le célèbre.', '{"en": {"text": "My body does wonders every day, and I celebrate it."}}'::jsonb),
  (2, 14, 'Je m’aime et j’ai envie de grandir : les deux vont ensemble.', '{"en": {"text": "I love myself and I want to grow: the two go together."}}'::jsonb),
  (2, 15, 'Plus je suis bienveillante avec moi, plus j’ai d’énergie à offrir.', '{"en": {"text": "The kinder I am to myself, the more energy I have to give."}}'::jsonb),
  (2, 16, 'Je fais taire ma critique intérieure et j’écoute ma force.', '{"en": {"text": "I quiet my inner critic and listen to my strength."}}'::jsonb),
  (2, 17, 'Je reconnais mes efforts, et je m’en félicite.', '{"en": {"text": "I recognise my efforts, and I congratulate myself."}}'::jsonb),
  (2, 18, 'Je me soutiens comme je soutiens celles que j’aime.', '{"en": {"text": "I support myself the way I support the women I love."}}'::jsonb),
  (2, 19, 'Mon corps est beau parce qu’il est vivant.', '{"en": {"text": "My body is beautiful because it is alive."}}'::jsonb),
  (2, 20, 'Je lâche le contrôle, et je gagne en liberté.', '{"en": {"text": "I let go of control, and I gain freedom."}}'::jsonb),
  (2, 21, 'Je suis patiente avec moi, et ma patience paie.', '{"en": {"text": "I am patient with myself, and my patience pays off."}}'::jsonb),
  (2, 22, 'Je vois ce qui va bien, et je construis dessus.', '{"en": {"text": "I see what is going well, and I build on it."}}'::jsonb),
  (2, 23, 'Je dis non à ce qui m’épuise et oui à ce qui me porte.', '{"en": {"text": "I say no to what drains me and yes to what lifts me."}}'::jsonb),
  (2, 24, 'Mes besoins comptent, et je les honore.', '{"en": {"text": "My needs matter, and I honour them."}}'::jsonb),
  (2, 25, 'Prendre soin de moi me donne de la force pour tout le reste.', '{"en": {"text": "Taking care of myself gives me strength for everything else."}}'::jsonb),
  (2, 26, 'Chaque respiration me rend mon pouvoir.', '{"en": {"text": "Every breath gives me back my power."}}'::jsonb),
  (2, 27, 'Je suis douce avec moi et déterminée dans mes choix.', '{"en": {"text": "I am gentle with myself and determined in my choices."}}'::jsonb),
  (2, 28, 'Je m’aime les jours difficiles aussi, et surtout ces jours-là.', '{"en": {"text": "I love myself on hard days too, and especially on those days."}}'::jsonb),
  (2, 29, 'Ce jour rare est une occasion de plus de prendre soin de moi.', '{"en": {"text": "This rare day is one more chance to take care of myself."}}'::jsonb),
  (3, 1, 'Je bouge parce que mon corps mérite de se sentir vivant.', '{"en": {"text": "I move because my body deserves to feel alive."}}'::jsonb),
  (3, 2, 'Le mouvement me rend mon énergie.', '{"en": {"text": "Movement gives me back my energy."}}'::jsonb),
  (3, 3, 'Mon corps est fait pour bouger, et il adore ça.', '{"en": {"text": "My body is made to move, and it loves it."}}'::jsonb),
  (3, 4, 'Je célèbre tout ce que mon corps peut faire aujourd’hui.', '{"en": {"text": "I celebrate everything my body can do today."}}'::jsonb),
  (3, 5, 'Chaque mouvement compte, et chaque mouvement me renforce.', '{"en": {"text": "Every movement counts, and every movement makes me stronger."}}'::jsonb),
  (3, 6, 'Je sens ma force grandir.', '{"en": {"text": "I feel my strength growing."}}'::jsonb),
  (3, 7, 'Je m’entraîne pour me sentir puissante, jamais pour me punir.', '{"en": {"text": "I train to feel powerful, never to punish myself."}}'::jsonb),
  (3, 8, 'Plus je me fais confiance, plus mon corps me surprend.', '{"en": {"text": "The more I trust myself, the more my body surprises me."}}'::jsonb),
  (3, 9, 'Mon souffle me donne de l’élan.', '{"en": {"text": "My breath gives me momentum."}}'::jsonb),
  (3, 10, 'Je sors de chaque séance plus vivante.', '{"en": {"text": "I leave every session feeling more alive."}}'::jsonb),
  (3, 11, 'Je donne ce que j’ai aujourd’hui, et c’est précieux.', '{"en": {"text": "I give what I have today, and it is precious."}}'::jsonb),
  (3, 12, 'J’adapte ma séance, et je la termine avec fierté.', '{"en": {"text": "I adapt my session, and I finish it with pride."}}'::jsonb),
  (3, 13, 'Je découvre chaque jour de nouvelles capacités.', '{"en": {"text": "Every day I discover new abilities."}}'::jsonb),
  (3, 14, 'Mes jambes me portent loin, mes bras me rendent forte.', '{"en": {"text": "My legs carry me far, my arms make me strong."}}'::jsonb),
  (3, 15, 'Bouger me remplit d’énergie pour toute la journée.', '{"en": {"text": "Moving fills me with energy for the whole day."}}'::jsonb),
  (3, 16, 'Je deviens plus solide, séance après séance.', '{"en": {"text": "I grow more solid, session after session."}}'::jsonb),
  (3, 17, 'Mon repos prépare mes prochains élans.', '{"en": {"text": "My rest prepares my next burst of energy."}}'::jsonb),
  (3, 18, 'Je choisis un mouvement qui me donne envie de sourire.', '{"en": {"text": "I choose a movement that makes me want to smile."}}'::jsonb),
  (3, 19, 'Chaque séance est un rendez-vous que je suis heureuse d’honorer.', '{"en": {"text": "Every session is a date I am happy to keep."}}'::jsonb),
  (3, 20, 'Je sens la vie circuler en moi quand je bouge.', '{"en": {"text": "I feel life flowing through me when I move."}}'::jsonb),
  (3, 21, 'Je progresse sans me faire mal.', '{"en": {"text": "I make progress without hurting myself."}}'::jsonb),
  (3, 22, 'Je prends de la place, et je l’assume.', '{"en": {"text": "I take up space, and I own it."}}'::jsonb),
  (3, 23, 'Ma force est réelle, même quand elle ne se voit pas.', '{"en": {"text": "My strength is real, even when it can’t be seen."}}'::jsonb),
  (3, 24, 'Je m’étire, je respire, je me sens prête.', '{"en": {"text": "I stretch, I breathe, I feel ready."}}'::jsonb),
  (3, 25, 'Le printemps réveille mon envie de bouger : je la suis.', '{"en": {"text": "Spring wakes up my urge to move: I follow it."}}'::jsonb),
  (3, 26, 'Je bouge avec joie et gratitude.', '{"en": {"text": "I move with joy and gratitude."}}'::jsonb),
  (3, 27, 'Mon corps est ma maison, et je la rends forte.', '{"en": {"text": "My body is my home, and I make it strong."}}'::jsonb),
  (3, 28, 'Je suis fière de chaque répétition.', '{"en": {"text": "I am proud of every single rep."}}'::jsonb),
  (3, 29, 'Aujourd’hui, je donne le meilleur de ce que j’ai, sans me juger.', '{"en": {"text": "Today, I give the best of what I have, without judging myself."}}'::jsonb),
  (3, 30, 'Je suis capable de plus que je ne l’imagine.', '{"en": {"text": "I am capable of more than I imagine."}}'::jsonb),
  (3, 31, 'Ma force m’appartient, et elle grandit.', '{"en": {"text": "My strength is mine, and it is growing."}}'::jsonb),
  (4, 1, 'J’ose prendre toute ma place.', '{"en": {"text": "I dare to take up all my space."}}'::jsonb),
  (4, 2, 'J’essaie, et c’est déjà une victoire.', '{"en": {"text": "I try, and that is already a win."}}'::jsonb),
  (4, 3, 'Ma peur me montre où grandir.', '{"en": {"text": "My fear shows me where to grow."}}'::jsonb),
  (4, 4, 'Il n’est jamais trop tard pour commencer.', '{"en": {"text": "It is never too late to begin."}}'::jsonb),
  (4, 5, 'J’ose changer de cap quand je le sens.', '{"en": {"text": "I dare to change course when I feel it."}}'::jsonb),
  (4, 6, 'Ma curiosité m’emmène plus loin que mes doutes.', '{"en": {"text": "My curiosity takes me further than my doubts."}}'::jsonb),
  (4, 7, 'Je n’ai pas besoin de tout savoir pour me lancer.', '{"en": {"text": "I don’t need to know everything to get started."}}'::jsonb),
  (4, 8, 'Aujourd’hui, je sors de ma zone de confort, juste un peu.', '{"en": {"text": "Today, I step out of my comfort zone, just a little."}}'::jsonb),
  (4, 9, 'Je me lance sans attendre la permission.', '{"en": {"text": "I go for it without waiting for permission."}}'::jsonb),
  (4, 10, 'Chaque essai me rend plus audacieuse.', '{"en": {"text": "Every attempt makes me bolder."}}'::jsonb),
  (4, 11, 'J’ose demander ce dont j’ai besoin.', '{"en": {"text": "I dare to ask for what I need."}}'::jsonb),
  (4, 12, 'Mes erreurs sont des marches, pas des murs.', '{"en": {"text": "My mistakes are steps, not walls."}}'::jsonb),
  (4, 13, 'Je dis oui à la nouveauté.', '{"en": {"text": "I say yes to what is new."}}'::jsonb),
  (4, 14, 'Je me fais confiance, et ça change tout.', '{"en": {"text": "I trust myself, and that changes everything."}}'::jsonb),
  (4, 15, 'Mon âge est une richesse, pas une limite.', '{"en": {"text": "My age is a richness, not a limit."}}'::jsonb),
  (4, 16, 'Ma voix compte, et je la fais entendre.', '{"en": {"text": "My voice matters, and I make it heard."}}'::jsonb),
  (4, 17, 'Aujourd’hui, je choisis l’élan.', '{"en": {"text": "Today, I choose momentum."}}'::jsonb),
  (4, 18, 'J’essaie une chose nouvelle, et je suis fière d’avoir osé.', '{"en": {"text": "I try something new, and I am proud that I dared."}}'::jsonb),
  (4, 19, 'J’ai le droit d’être débutante et de m’amuser.', '{"en": {"text": "I have the right to be a beginner and to have fun."}}'::jsonb),
  (4, 20, 'J’ose être vue telle que je suis.', '{"en": {"text": "I dare to be seen as I am."}}'::jsonb),
  (4, 21, 'Je suis capable de choses que je n’ai pas encore essayées.', '{"en": {"text": "I am capable of things I haven’t tried yet."}}'::jsonb),
  (4, 22, 'Mes envies méritent que je passe à l’action.', '{"en": {"text": "My desires deserve my action."}}'::jsonb),
  (4, 23, 'J’avance avec mes doutes, et j’avance quand même.', '{"en": {"text": "I move forward with my doubts, and I move forward anyway."}}'::jsonb),
  (4, 24, 'Je choisis pour moi, pas pour le regard des autres.', '{"en": {"text": "I choose for myself, not for the eyes of others."}}'::jsonb),
  (4, 25, 'Je peux toujours recommencer autrement.', '{"en": {"text": "I can always start again differently."}}'::jsonb),
  (4, 26, 'L’inconfort de la nouveauté est le signe que je grandis.', '{"en": {"text": "The discomfort of something new is the sign that I am growing."}}'::jsonb),
  (4, 27, 'J’ose suivre mon propre rythme dans un monde pressé.', '{"en": {"text": "I dare to follow my own rhythm in a world in a hurry."}}'::jsonb),
  (4, 28, 'Chaque oui que je me dis me rend plus forte.', '{"en": {"text": "Every yes I say to myself makes me stronger."}}'::jsonb),
  (4, 29, 'Plus j’ose, plus je me découvre.', '{"en": {"text": "The more I dare, the more I discover myself."}}'::jsonb),
  (4, 30, 'Ce mois-ci, j’ai osé, et je continue.', '{"en": {"text": "This month I dared, and I keep going."}}'::jsonb),
  (5, 1, 'Je nourris mon corps pour qu’il me porte loin.', '{"en": {"text": "I nourish my body so it can carry me far."}}'::jsonb),
  (5, 2, 'Chaque repas est une occasion de prendre soin de moi.', '{"en": {"text": "Every meal is a chance to take care of myself."}}'::jsonb),
  (5, 3, 'J’écoute ma faim : elle est mon alliée.', '{"en": {"text": "I listen to my hunger: it is my ally."}}'::jsonb),
  (5, 4, 'Je mange pour avoir de l’énergie, du plaisir et de la force.', '{"en": {"text": "I eat for energy, pleasure and strength."}}'::jsonb),
  (5, 5, 'Je savoure, et je me sens bien.', '{"en": {"text": "I savour, and I feel good."}}'::jsonb),
  (5, 6, 'Une assiette simple peut me donner beaucoup d’énergie.', '{"en": {"text": "A simple plate can give me so much energy."}}'::jsonb),
  (5, 7, 'Je mange en conscience, et je me sens libre.', '{"en": {"text": "I eat mindfully, and I feel free."}}'::jsonb),
  (5, 8, 'Le plaisir fait partie de ma façon de bien manger.', '{"en": {"text": "Pleasure is part of how I eat well."}}'::jsonb),
  (5, 9, 'Je m’hydrate, et mon corps me dit merci.', '{"en": {"text": "I hydrate, and my body thanks me."}}'::jsonb),
  (5, 10, 'Je reconnais la satiété, et je lui fais confiance.', '{"en": {"text": "I recognise when I am full, and I trust that feeling."}}'::jsonb),
  (5, 11, 'Je nourris aussi mon esprit de lectures, de rencontres et d’idées.', '{"en": {"text": "I also feed my mind with books, encounters and ideas."}}'::jsonb),
  (5, 12, 'Un repas partagé me remplit de joie.', '{"en": {"text": "A shared meal fills me with joy."}}'::jsonb),
  (5, 13, 'Je ne compense pas : je continue, confiante.', '{"en": {"text": "I don’t make up for anything: I carry on, confident."}}'::jsonb),
  (5, 14, 'Cuisiner pour moi, c’est me dire que je compte.', '{"en": {"text": "Cooking for myself is telling myself that I matter."}}'::jsonb),
  (5, 15, 'Je choisis des aliments qui me donnent de l’élan.', '{"en": {"text": "I choose foods that give me momentum."}}'::jsonb),
  (5, 16, 'Tous mes repas ont leur place : je mange sans me juger.', '{"en": {"text": "All my meals have their place: I eat without judging myself."}}'::jsonb),
  (5, 17, 'Je m’assois, je savoure, je recharge.', '{"en": {"text": "I sit down, I savour, I recharge."}}'::jsonb),
  (5, 18, 'Mon corps sait ce qu’il lui faut, et je l’écoute.', '{"en": {"text": "My body knows what it needs, and I listen."}}'::jsonb),
  (5, 19, 'Ce que je mets dans mon assiette me donne de la force.', '{"en": {"text": "What I put on my plate gives me strength."}}'::jsonb),
  (5, 20, 'La gourmandise fait partie de mon équilibre.', '{"en": {"text": "Indulgence is part of my balance."}}'::jsonb),
  (5, 21, 'Je nourris mon corps pour vivre pleinement.', '{"en": {"text": "I nourish my body to live fully."}}'::jsonb),
  (5, 22, 'Chaque repas est un nouveau départ, jamais un rattrapage.', '{"en": {"text": "Every meal is a fresh start, never a way to make amends."}}'::jsonb),
  (5, 23, 'Je redécouvre le goût des choses simples.', '{"en": {"text": "I rediscover the taste of simple things."}}'::jsonb),
  (5, 24, 'Mon assiette colorée me donne de l’énergie.', '{"en": {"text": "My colourful plate gives me energy."}}'::jsonb),
  (5, 25, 'Après un repas, je me sens nourrie, pas coupable.', '{"en": {"text": "After a meal, I feel nourished, not guilty."}}'::jsonb),
  (5, 26, 'L’eau que je bois me revitalise.', '{"en": {"text": "The water I drink revitalises me."}}'::jsonb),
  (5, 27, 'Chaque repas m’aide à faire la paix avec la nourriture.', '{"en": {"text": "Every meal helps me make peace with food."}}'::jsonb),
  (5, 28, 'Bien manger, c’est se faire plaisir et se faire du bien.', '{"en": {"text": "Eating well means enjoying myself and doing myself good."}}'::jsonb),
  (5, 29, 'Je nourris mes projets avec la même énergie que mon corps.', '{"en": {"text": "I feed my projects with the same energy as my body."}}'::jsonb),
  (5, 30, 'Ma relation à la nourriture est sereine et joyeuse.', '{"en": {"text": "My relationship with food is calm and joyful."}}'::jsonb),
  (5, 31, 'Je me nourris de tout ce qui me fait grandir.', '{"en": {"text": "I feed myself with everything that makes me grow."}}'::jsonb),
  (6, 1, 'Je fais confiance à ma capacité de trouver mon chemin.', '{"en": {"text": "I trust my ability to find my way."}}'::jsonb),
  (6, 2, 'Je laisse ma lumière briller sans m’excuser.', '{"en": {"text": "I let my light shine without apologising."}}'::jsonb),
  (6, 3, 'Je suis fière de la femme que je deviens.', '{"en": {"text": "I am proud of the woman I am becoming."}}'::jsonb),
  (6, 4, 'Je porte mon corps avec assurance.', '{"en": {"text": "I carry my body with confidence."}}'::jsonb),
  (6, 5, 'Mon intuition me guide, et je la suis.', '{"en": {"text": "My intuition guides me, and I follow it."}}'::jsonb),
  (6, 6, 'Je connais ma valeur.', '{"en": {"text": "I know my worth."}}'::jsonb),
  (6, 7, 'Je me sens bien dans mon corps, et je le montre.', '{"en": {"text": "I feel good in my body, and it shows."}}'::jsonb),
  (6, 8, 'Je m’affirme avec calme et fermeté.', '{"en": {"text": "I assert myself calmly and firmly."}}'::jsonb),
  (6, 9, 'Chaque promesse tenue envers moi renforce ma confiance.', '{"en": {"text": "Every promise I keep to myself strengthens my confidence."}}'::jsonb),
  (6, 10, 'Je reconnais mes talents, et je les mets en lumière.', '{"en": {"text": "I recognise my talents, and I bring them into the light."}}'::jsonb),
  (6, 11, 'Je suis à ma place, et je vais plus loin.', '{"en": {"text": "I am where I belong, and I am going further."}}'::jsonb),
  (6, 12, 'Je m’habille pour me sentir puissante.', '{"en": {"text": "I dress to feel powerful."}}'::jsonb),
  (6, 13, 'Je sors, je bouge, je vis : je n’attends plus.', '{"en": {"text": "I go out, I move, I live: I am done waiting."}}'::jsonb),
  (6, 14, 'La lumière du jour me recharge.', '{"en": {"text": "Daylight recharges me."}}'::jsonb),
  (6, 15, 'Je parle de moi avec fierté.', '{"en": {"text": "I speak about myself with pride."}}'::jsonb),
  (6, 16, 'Je sais ce que je veux, et j’y vais.', '{"en": {"text": "I know what I want, and I go for it."}}'::jsonb),
  (6, 17, 'Je me tiens droite, dans mon corps et dans mes choix.', '{"en": {"text": "I stand tall, in my body and in my choices."}}'::jsonb),
  (6, 18, 'Ma présence fait la différence.', '{"en": {"text": "My presence makes a difference."}}'::jsonb),
  (6, 19, 'Je crois en moi, un peu plus chaque jour.', '{"en": {"text": "I believe in myself, a little more every day."}}'::jsonb),
  (6, 20, 'Ce qui me rend unique est ma force.', '{"en": {"text": "What makes me unique is my strength."}}'::jsonb),
  (6, 21, 'Même quand je doute, je reste de mon côté.', '{"en": {"text": "Even when I doubt, I stay on my own side."}}'::jsonb),
  (6, 22, 'Je suis capable de traverser tout ce qui se présente.', '{"en": {"text": "I am capable of getting through whatever comes."}}'::jsonb),
  (6, 23, 'Mes choix m’appartiennent, et je les assume.', '{"en": {"text": "My choices are mine, and I own them."}}'::jsonb),
  (6, 24, 'Je rayonne à ma manière.', '{"en": {"text": "I shine in my own way."}}'::jsonb),
  (6, 25, 'Je suis fière de moi, et je me le dis.', '{"en": {"text": "I am proud of myself, and I tell myself so."}}'::jsonb),
  (6, 26, 'Je tiens mes promesses envers moi-même.', '{"en": {"text": "I keep the promises I make to myself."}}'::jsonb),
  (6, 27, 'Mon corps est prêt pour l’été, tel qu’il est.', '{"en": {"text": "My body is ready for summer, just as it is."}}'::jsonb),
  (6, 28, 'J’accueille les compliments : je les mérite.', '{"en": {"text": "I welcome compliments: I deserve them."}}'::jsonb),
  (6, 29, 'Je suis solide, même quand je vacille.', '{"en": {"text": "I am solid, even when I waver."}}'::jsonb),
  (6, 30, 'J’entre dans l’été confiante et pleine d’énergie.', '{"en": {"text": "I step into summer confident and full of energy."}}'::jsonb),
  (7, 1, 'Le repos est ce qui me rend plus forte.', '{"en": {"text": "Rest is what makes me stronger."}}'::jsonb),
  (7, 2, 'Je fais une pause pour mieux repartir.', '{"en": {"text": "I take a break so I can set off again."}}'::jsonb),
  (7, 3, 'Me reposer, c’est investir en moi.', '{"en": {"text": "Resting is investing in myself."}}'::jsonb),
  (7, 4, 'La lenteur me rend mon énergie.', '{"en": {"text": "Slowness gives me back my energy."}}'::jsonb),
  (7, 5, 'Je ralentis pour mieux ressentir et mieux choisir.', '{"en": {"text": "I slow down to feel better and choose better."}}'::jsonb),
  (7, 6, 'Mon corps se reconstruit pendant que je me repose.', '{"en": {"text": "My body rebuilds itself while I rest."}}'::jsonb),
  (7, 7, 'Je profite des longues journées pour faire ce que j’aime.', '{"en": {"text": "I use the long days to do what I love."}}'::jsonb),
  (7, 8, 'Mon sommeil est mon meilleur allié.', '{"en": {"text": "My sleep is my best ally."}}'::jsonb),
  (7, 9, 'Je décroche, et je reviens plus claire.', '{"en": {"text": "I switch off, and I come back clearer."}}'::jsonb),
  (7, 10, 'Une journée calme recharge mes batteries.', '{"en": {"text": "A quiet day recharges my batteries."}}'::jsonb),
  (7, 11, 'Je m’offre du temps pour rêver grand.', '{"en": {"text": "I give myself time to dream big."}}'::jsonb),
  (7, 12, 'Je laisse mon esprit vagabonder : il revient avec des idées.', '{"en": {"text": "I let my mind wander: it comes back with ideas."}}'::jsonb),
  (7, 13, 'Je respire profondément, et je retrouve mon énergie.', '{"en": {"text": "I breathe deeply, and I find my energy again."}}'::jsonb),
  (7, 14, 'Ma valeur ne dépend pas de ma productivité.', '{"en": {"text": "My worth does not depend on my productivity."}}'::jsonb),
  (7, 15, 'Je vis mes vacances pleinement, sans chercher à les optimiser.', '{"en": {"text": "I live my holidays fully, without trying to optimise them."}}'::jsonb),
  (7, 16, 'Je bouge pour le plaisir : nager, marcher, danser.', '{"en": {"text": "I move for pleasure: swimming, walking, dancing."}}'::jsonb),
  (7, 17, 'J’écoute ma fatigue avant qu’elle ne crie.', '{"en": {"text": "I listen to my tiredness before it shouts."}}'::jsonb),
  (7, 18, 'Le silence me recharge.', '{"en": {"text": "Silence recharges me."}}'::jsonb),
  (7, 19, 'Je ferme les yeux, et je fais le plein.', '{"en": {"text": "I close my eyes, and I fill up again."}}'::jsonb),
  (7, 20, 'Mes rituels évoluent avec les saisons, et je reste fidèle à moi.', '{"en": {"text": "My rituals change with the seasons, and I stay true to myself."}}'::jsonb),
  (7, 21, 'Je savoure l’instant, pleinement.', '{"en": {"text": "I savour the moment, fully."}}'::jsonb),
  (7, 22, 'Le soleil, l’eau et le vent me remplissent d’énergie.', '{"en": {"text": "Sun, water and wind fill me with energy."}}'::jsonb),
  (7, 23, 'Je ralentis, mais je ne m’arrête pas.', '{"en": {"text": "I slow down, but I don’t stop."}}'::jsonb),
  (7, 24, 'Bien dormir, c’est me donner les moyens de mes envies.', '{"en": {"text": "Sleeping well gives me the means to follow my desires."}}'::jsonb),
  (7, 25, 'Je m’accorde des matins libres, et j’en ressors ressourcée.', '{"en": {"text": "I give myself free mornings, and I come out of them renewed."}}'::jsonb),
  (7, 26, 'Je choisis d’être présente plutôt que pressée.', '{"en": {"text": "I choose to be present rather than in a hurry."}}'::jsonb),
  (7, 27, 'En été, j’allège mes rituels sans les perdre.', '{"en": {"text": "In summer, I lighten my rituals without losing them."}}'::jsonb),
  (7, 28, 'Aujourd’hui, je range la liste et je profite.', '{"en": {"text": "Today, I put the list away and I enjoy."}}'::jsonb),
  (7, 29, 'Savoir me reposer est une preuve d’intelligence.', '{"en": {"text": "Knowing how to rest is a sign of intelligence."}}'::jsonb),
  (7, 30, 'Dans le calme, je retrouve ma clarté.', '{"en": {"text": "In the calm, I find my clarity again."}}'::jsonb),
  (7, 31, 'Je reviens de chaque pause avec encore plus d’élan.', '{"en": {"text": "I come back from every break with even more momentum."}}'::jsonb),
  (8, 1, 'Je vis ce jour pleinement.', '{"en": {"text": "I live this day fully."}}'::jsonb),
  (8, 2, 'Je savoure chaque moment, et je m’en nourris.', '{"en": {"text": "I savour every moment, and it feeds me."}}'::jsonb),
  (8, 3, 'Le plaisir me donne de l’énergie.', '{"en": {"text": "Pleasure gives me energy."}}'::jsonb),
  (8, 4, 'J’ouvre grand mes sens.', '{"en": {"text": "I open my senses wide."}}'::jsonb),
  (8, 5, 'Je ris, et tout devient plus léger.', '{"en": {"text": "I laugh, and everything feels lighter."}}'::jsonb),
  (8, 6, 'Je profite de mon corps, je ne le juge plus.', '{"en": {"text": "I enjoy my body; I no longer judge it."}}'::jsonb),
  (8, 7, 'Chaque sensation me rappelle que je suis vivante.', '{"en": {"text": "Every sensation reminds me that I am alive."}}'::jsonb),
  (8, 8, 'Je crée les moments qui me rendent heureuse.', '{"en": {"text": "I create the moments that make me happy."}}'::jsonb),
  (8, 9, 'J’accueille la joie à bras ouverts.', '{"en": {"text": "I welcome joy with open arms."}}'::jsonb),
  (8, 10, 'Je lève les yeux de mon écran, et je vis.', '{"en": {"text": "I look up from my screen, and I live."}}'::jsonb),
  (8, 11, 'Mon corps est fait pour vivre, pas seulement pour être regardé.', '{"en": {"text": "My body is made for living, not just for being looked at."}}'::jsonb),
  (8, 12, 'Je danse, même seule dans ma cuisine.', '{"en": {"text": "I dance, even alone in my kitchen."}}'::jsonb),
  (8, 13, 'Je m’offre un plaisir, et je le savoure sans me justifier.', '{"en": {"text": "I treat myself, and I savour it without justifying myself."}}'::jsonb),
  (8, 14, 'L’instant présent est plein de possibles.', '{"en": {"text": "The present moment is full of possibilities."}}'::jsonb),
  (8, 15, 'Mes sens me reconnectent à l’essentiel.', '{"en": {"text": "My senses reconnect me with what matters."}}'::jsonb),
  (8, 16, 'Je célèbre les petites victoires du quotidien.', '{"en": {"text": "I celebrate the small wins of everyday life."}}'::jsonb),
  (8, 17, 'Je suis pleinement présente pour ceux que j’aime.', '{"en": {"text": "I am fully present for the people I love."}}'::jsonb),
  (8, 18, 'Je goûte la chaleur, la lumière, la liberté.', '{"en": {"text": "I taste the warmth, the light, the freedom."}}'::jsonb),
  (8, 19, 'Je choisis la joie, sans attendre de raison.', '{"en": {"text": "I choose joy, without waiting for a reason."}}'::jsonb),
  (8, 20, 'J’observe le monde avec curiosité.', '{"en": {"text": "I look at the world with curiosity."}}'::jsonb),
  (8, 21, 'Mon attention est un pouvoir, et je choisis où la poser.', '{"en": {"text": "My attention is a power, and I choose where to place it."}}'::jsonb),
  (8, 22, 'Je vis ce moment au lieu de le photographier.', '{"en": {"text": "I live this moment instead of photographing it."}}'::jsonb),
  (8, 23, 'Aujourd’hui, je crée un souvenir.', '{"en": {"text": "Today, I create a memory."}}'::jsonb),
  (8, 24, 'Je bouge comme on joue : librement, joyeusement.', '{"en": {"text": "I move the way we play: freely, joyfully."}}'::jsonb),
  (8, 25, 'Je sens la terre sous mes pieds et la force en moi.', '{"en": {"text": "I feel the earth beneath my feet and the strength within me."}}'::jsonb),
  (8, 26, 'Je m’émerveille, et mon énergie se renouvelle.', '{"en": {"text": "I marvel, and my energy is renewed."}}'::jsonb),
  (8, 27, 'La légèreté me va bien.', '{"en": {"text": "Lightness suits me."}}'::jsonb),
  (8, 28, 'Je m’engage pleinement dans ce que je fais.', '{"en": {"text": "I commit fully to what I do."}}'::jsonb),
  (8, 29, 'Même un jour ordinaire peut devenir un beau jour.', '{"en": {"text": "Even an ordinary day can become a beautiful one."}}'::jsonb),
  (8, 30, 'Chaque respiration me ramène à ma force.', '{"en": {"text": "Every breath brings me back to my strength."}}'::jsonb),
  (8, 31, 'Je garde l’énergie de l’été pour la suite.', '{"en": {"text": "I keep the energy of summer for what comes next."}}'::jsonb),
  (9, 1, 'Je reprends mes rituels avec envie.', '{"en": {"text": "I return to my rituals with enthusiasm."}}'::jsonb),
  (9, 2, 'Cette rentrée, je la vis à ma façon.', '{"en": {"text": "This new season, I live it my own way."}}'::jsonb),
  (9, 3, 'Mes rituels me portent.', '{"en": {"text": "My rituals carry me."}}'::jsonb),
  (9, 4, 'Je commence ma journée par un geste qui me renforce.', '{"en": {"text": "I begin my day with a gesture that makes me stronger."}}'::jsonb),
  (9, 5, 'Je construis des habitudes qui me font du bien.', '{"en": {"text": "I build habits that do me good."}}'::jsonb),
  (9, 6, 'Ma régularité me rend libre.', '{"en": {"text": "My consistency sets me free."}}'::jsonb),
  (9, 7, 'Je protège mon temps pour moi comme un rendez-vous important.', '{"en": {"text": "I protect my time for myself like an important appointment."}}'::jsonb),
  (9, 8, 'Un rituel simple, tenu, peut tout changer.', '{"en": {"text": "A simple ritual, kept, can change everything."}}'::jsonb),
  (9, 9, 'Je planifie avec souplesse, et je m’y tiens avec plaisir.', '{"en": {"text": "I plan with flexibility, and I stick to it with pleasure."}}'::jsonb),
  (9, 10, 'Bouger, bien manger, respirer, dormir : je reviens à l’essentiel.', '{"en": {"text": "Moving, eating well, breathing, sleeping: I return to what matters."}}'::jsonb),
  (9, 11, 'Je prépare ma semaine pour qu’elle me serve.', '{"en": {"text": "I prepare my week so that it serves me."}}'::jsonb),
  (9, 12, 'Je reprends une chose à la fois, et je la fais bien.', '{"en": {"text": "I pick up one thing at a time, and I do it well."}}'::jsonb),
  (9, 13, 'Mes ancrages me gardent stable quand tout bouge.', '{"en": {"text": "My anchors keep me steady when everything moves."}}'::jsonb),
  (9, 14, 'Mon matin m’appartient, et il donne le ton de ma journée.', '{"en": {"text": "My morning is mine, and it sets the tone for my day."}}'::jsonb),
  (9, 15, 'Je bouge un peu chaque jour, et chaque jour compte.', '{"en": {"text": "I move a little every day, and every day counts."}}'::jsonb),
  (9, 16, 'Mon rituel du soir me prépare à un nouveau départ.', '{"en": {"text": "My evening ritual prepares me for a fresh start."}}'::jsonb),
  (9, 17, 'J’organise ma vie autour de ce qui compte pour moi.', '{"en": {"text": "I organise my life around what matters to me."}}'::jsonb),
  (9, 18, 'J’ajuste mes rituels, je ne les abandonne pas.', '{"en": {"text": "I adjust my rituals; I don’t abandon them."}}'::jsonb),
  (9, 19, 'Ma constance naît de l’envie, pas de la contrainte.', '{"en": {"text": "My constancy comes from desire, not from constraint."}}'::jsonb),
  (9, 20, 'Chaque geste répété devient une force tranquille.', '{"en": {"text": "Every repeated gesture becomes a quiet strength."}}'::jsonb),
  (9, 21, 'Même dans une semaine chargée, je garde un moment pour moi.', '{"en": {"text": "Even in a busy week, I keep a moment for myself."}}'::jsonb),
  (9, 22, 'Je commence petit, et je vais loin.', '{"en": {"text": "I start small, and I go far."}}'::jsonb),
  (9, 23, 'Je rends mon quotidien beau.', '{"en": {"text": "I make my everyday life beautiful."}}'::jsonb),
  (9, 24, 'Je fais de la place pour ce qui me nourrit.', '{"en": {"text": "I make room for what nourishes me."}}'::jsonb),
  (9, 25, 'Je trouve mon rythme de rentrée, et je m’y tiens.', '{"en": {"text": "I find my rhythm for the new season, and I keep to it."}}'::jsonb),
  (9, 26, 'Chaque rituel est une promesse que je tiens envers moi.', '{"en": {"text": "Every ritual is a promise I keep to myself."}}'::jsonb),
  (9, 27, 'Je me concentre sur ce qui dépend de moi.', '{"en": {"text": "I focus on what is up to me."}}'::jsonb),
  (9, 28, 'Je reste souple face à l’imprévu.', '{"en": {"text": "I stay flexible when the unexpected comes."}}'::jsonb),
  (9, 29, 'Je choisis la simplicité, et j’avance plus sereinement.', '{"en": {"text": "I choose simplicity, and I move forward more calmly."}}'::jsonb),
  (9, 30, 'Je suis fière du quotidien que je construis.', '{"en": {"text": "I am proud of the everyday life I am building."}}'::jsonb),
  (10, 1, 'Je lâche ce qui me freine.', '{"en": {"text": "I let go of what holds me back."}}'::jsonb),
  (10, 2, 'Je laisse partir ce que je ne contrôle pas, et je gagne en énergie.', '{"en": {"text": "I release what I can’t control, and I gain energy."}}'::jsonb),
  (10, 3, 'Demander de l’aide est une force.', '{"en": {"text": "Asking for help is a strength."}}'::jsonb),
  (10, 4, 'Je remplace mes attentes irréalistes par des pas concrets.', '{"en": {"text": "I replace unrealistic expectations with concrete steps."}}'::jsonb),
  (10, 5, 'Je me libère des « il faudrait », et je choisis.', '{"en": {"text": "I free myself from the “I should”, and I choose."}}'::jsonb),
  (10, 6, 'Le changement est mon allié.', '{"en": {"text": "Change is my ally."}}'::jsonb),
  (10, 7, 'Je trace mon propre chemin, sans me comparer.', '{"en": {"text": "I carve my own path, without comparing myself."}}'::jsonb),
  (10, 8, 'Les jours plus lents font aussi partie de mon chemin.', '{"en": {"text": "Slower days are part of my path too."}}'::jsonb),
  (10, 9, 'Je pardonne mes erreurs, et je repars.', '{"en": {"text": "I forgive my mistakes, and I set off again."}}'::jsonb),
  (10, 10, 'Je quitte l’idée d’un corps idéal pour vivre pleinement dans le mien.', '{"en": {"text": "I leave behind the idea of an ideal body to live fully in mine."}}'::jsonb),
  (10, 11, 'Le temps travaille pour moi.', '{"en": {"text": "Time is working for me."}}'::jsonb),
  (10, 12, 'Je relâche mes épaules, ma mâchoire, mes doutes.', '{"en": {"text": "I relax my shoulders, my jaw, my doubts."}}'::jsonb),
  (10, 13, 'Je n’ai pas besoin de toutes les réponses pour avancer.', '{"en": {"text": "I don’t need all the answers to move forward."}}'::jsonb),
  (10, 14, 'Je choisis ma paix plutôt que d’avoir raison.', '{"en": {"text": "I choose my peace over being right."}}'::jsonb),
  (10, 15, 'Je laisse passer les pensées qui ne me servent pas.', '{"en": {"text": "I let the thoughts that don’t serve me pass by."}}'::jsonb),
  (10, 16, 'Je me libère de ce qui m’épuise.', '{"en": {"text": "I free myself from what drains me."}}'::jsonb),
  (10, 17, 'Je fais de la place pour ce qui arrive de beau.', '{"en": {"text": "I make room for the good that is coming."}}'::jsonb),
  (10, 18, 'Je peux changer de direction et rester fidèle à moi.', '{"en": {"text": "I can change direction and stay true to myself."}}'::jsonb),
  (10, 19, 'J’accepte ce qui est, et je choisis ce qui sera.', '{"en": {"text": "I accept what is, and I choose what will be."}}'::jsonb),
  (10, 20, 'Je préfère avancer imparfaitement que rester immobile.', '{"en": {"text": "I would rather move forward imperfectly than stand still."}}'::jsonb),
  (10, 21, 'J’expire ce qui pèse, j’inspire ce qui me porte.', '{"en": {"text": "I breathe out what weighs on me, I breathe in what lifts me."}}'::jsonb),
  (10, 22, 'Je me concentre sur ce que je peux faire, pas sur ce que les autres pensent.', '{"en": {"text": "I focus on what I can do, not on what others think."}}'::jsonb),
  (10, 23, 'Je change avec la saison, et je me renouvelle.', '{"en": {"text": "I change with the season, and I renew myself."}}'::jsonb),
  (10, 24, 'J’ose dire « ça suffit » pour dire oui à moi.', '{"en": {"text": "I dare to say “enough” so I can say yes to myself."}}'::jsonb),
  (10, 25, 'Je n’ai plus besoin de me justifier pour avancer.', '{"en": {"text": "I no longer need to justify myself to move forward."}}'::jsonb),
  (10, 26, 'Plus je lâche, plus je suis libre.', '{"en": {"text": "The more I let go, the freer I am."}}'::jsonb),
  (10, 27, 'Après chaque jour sans élan, l’énergie revient.', '{"en": {"text": "After every day without momentum, the energy returns."}}'::jsonb),
  (10, 28, 'Je fais confiance au chemin, même quand il est lent.', '{"en": {"text": "I trust the path, even when it is slow."}}'::jsonb),
  (10, 29, 'Je savoure la route autant que l’arrivée.', '{"en": {"text": "I savour the road as much as the arrival."}}'::jsonb),
  (10, 30, 'Je laisse derrière moi ce qui me retenait.', '{"en": {"text": "I leave behind what was holding me back."}}'::jsonb),
  (10, 31, 'Je me défais de l’inutile pour garder l’essentiel.', '{"en": {"text": "I shed what is unnecessary to keep what is essential."}}'::jsonb),
  (11, 1, 'Ma force vient de l’intérieur.', '{"en": {"text": "My strength comes from within."}}'::jsonb),
  (11, 2, 'Je reviens à mon souffle, et je retrouve ma puissance.', '{"en": {"text": "I return to my breath, and I find my power again."}}'::jsonb),
  (11, 3, 'Les pieds sur le sol, je me sens solide.', '{"en": {"text": "Feet on the ground, I feel solid."}}'::jsonb),
  (11, 4, 'Je trouve en moi la stabilité dont j’ai besoin.', '{"en": {"text": "I find within me the stability I need."}}'::jsonb),
  (11, 5, 'Je profite des soirées douces pour me ressourcer.', '{"en": {"text": "I enjoy the gentle evenings to restore myself."}}'::jsonb),
  (11, 6, 'Je me tourne vers l’intérieur pour mieux rayonner.', '{"en": {"text": "I turn inward so I can shine brighter."}}'::jsonb),
  (11, 7, 'Je suis enracinée dans ce qui compte pour moi.', '{"en": {"text": "I am rooted in what matters to me."}}'::jsonb),
  (11, 8, 'Je protège mon énergie quand les jours raccourcissent.', '{"en": {"text": "I protect my energy as the days grow shorter."}}'::jsonb),
  (11, 9, 'Mon calme est un refuge que j’emporte partout.', '{"en": {"text": "My calm is a refuge I carry everywhere."}}'::jsonb),
  (11, 10, 'Je m’écoute, et je sais quoi faire.', '{"en": {"text": "I listen to myself, and I know what to do."}}'::jsonb),
  (11, 11, 'Quelques respirations suffisent à me recentrer.', '{"en": {"text": "A few breaths are enough to centre me again."}}'::jsonb),
  (11, 12, 'Je m’enveloppe de chaleur, et je repars.', '{"en": {"text": "I wrap myself in warmth, and I set off again."}}'::jsonb),
  (11, 13, 'Mes repères me rendent libre.', '{"en": {"text": "My bearings set me free."}}'::jsonb),
  (11, 14, 'Je cultive ma paix intérieure chaque jour.', '{"en": {"text": "I cultivate my inner peace every day."}}'::jsonb),
  (11, 15, 'Mon corps est mon point d’appui.', '{"en": {"text": "My body is my foundation."}}'::jsonb),
  (11, 16, 'Je laisse le froid dehors et je garde le feu en moi.', '{"en": {"text": "I leave the cold outside and keep the fire within me."}}'::jsonb),
  (11, 17, 'Je ralentis sans m’éteindre.', '{"en": {"text": "I slow down without dimming my light."}}'::jsonb),
  (11, 18, 'J’écris ce que je ressens, et j’y vois plus clair.', '{"en": {"text": "I write what I feel, and I see more clearly."}}'::jsonb),
  (11, 19, 'Je me sens chez moi dans mon corps.', '{"en": {"text": "I feel at home in my body."}}'::jsonb),
  (11, 20, 'Je prends le temps de ressentir, puis j’agis.', '{"en": {"text": "I take the time to feel, then I act."}}'::jsonb),
  (11, 21, 'Ma richesse intérieure m’inspire.', '{"en": {"text": "My inner richness inspires me."}}'::jsonb),
  (11, 22, 'Je me nourris de chaleur : un plat, une couverture, une présence.', '{"en": {"text": "I feed myself with warmth: a dish, a blanket, a presence."}}'::jsonb),
  (11, 23, 'Je bouge pour me réchauffer et réveiller mon énergie.', '{"en": {"text": "I move to warm up and wake my energy."}}'::jsonb),
  (11, 24, 'Je reste fidèle à moi-même, même dans la tempête.', '{"en": {"text": "I stay true to myself, even in the storm."}}'::jsonb),
  (11, 25, 'Quand il fait sombre, j’allume ma propre lumière.', '{"en": {"text": "When it gets dark, I switch on my own light."}}'::jsonb),
  (11, 26, 'Je sais toujours revenir à mon centre.', '{"en": {"text": "I always know how to return to my centre."}}'::jsonb),
  (11, 27, 'Je suis pleinement présente à ce que je vis.', '{"en": {"text": "I am fully present to what I am living."}}'::jsonb),
  (11, 28, 'Mes valeurs guident chacune de mes décisions.', '{"en": {"text": "My values guide every one of my decisions."}}'::jsonb),
  (11, 29, 'Je crée autour de moi un espace qui me ressource.', '{"en": {"text": "I create a space around me that restores me."}}'::jsonb),
  (11, 30, 'Je reste stable, même quand le monde vacille.', '{"en": {"text": "I stay steady, even when the world wavers."}}'::jsonb),
  (12, 1, 'Je remercie mon corps pour tout ce qu’il a traversé cette année.', '{"en": {"text": "I thank my body for everything it has been through this year."}}'::jsonb),
  (12, 2, 'Je suis reconnaissante pour chaque petite victoire.', '{"en": {"text": "I am grateful for every small win."}}'::jsonb),
  (12, 3, 'Je regarde le chemin parcouru, et je suis fière.', '{"en": {"text": "I look at how far I have come, and I am proud."}}'::jsonb),
  (12, 4, 'Je célèbre tout ce que j’ai accompli cette année.', '{"en": {"text": "I celebrate everything I have accomplished this year."}}'::jsonb),
  (12, 5, 'Je remercie la femme que j’ai été, et j’accueille celle que je deviens.', '{"en": {"text": "I thank the woman I was, and I welcome the one I am becoming."}}'::jsonb),
  (12, 6, 'La gratitude me donne de l’élan.', '{"en": {"text": "Gratitude gives me momentum."}}'::jsonb),
  (12, 7, 'Je garde en moi les moments qui m’ont rendue plus forte.', '{"en": {"text": "I keep within me the moments that made me stronger."}}'::jsonb),
  (12, 8, 'Je remercie les personnes qui me soutiennent.', '{"en": {"text": "I thank the people who support me."}}'::jsonb),
  (12, 9, 'Je vis les fêtes pleinement, sans compter.', '{"en": {"text": "I live the holidays fully, without keeping count."}}'::jsonb),
  (12, 10, 'Je savoure les repas de fête avec joie.', '{"en": {"text": "I savour festive meals with joy."}}'::jsonb),
  (12, 11, 'Je suis fière de moi, sans attendre la perfection.', '{"en": {"text": "I am proud of myself, without waiting for perfection."}}'::jsonb),
  (12, 12, 'Je termine l’année la tête haute.', '{"en": {"text": "I end the year with my head held high."}}'::jsonb),
  (12, 13, 'Je me souviens de ma force dans les moments difficiles.', '{"en": {"text": "I remember my strength in difficult moments."}}'::jsonb),
  (12, 14, 'Je m’offre du temps, le plus beau des cadeaux.', '{"en": {"text": "I give myself time, the most beautiful gift."}}'::jsonb),
  (12, 15, 'Mon esprit a été courageux cette année, et je le salue.', '{"en": {"text": "My mind was brave this year, and I salute it."}}'::jsonb),
  (12, 16, 'Chaque jour de cette année m’a fait grandir.', '{"en": {"text": "Every day of this year has made me grow."}}'::jsonb),
  (12, 17, 'Je suis reconnaissante d’être là, maintenant.', '{"en": {"text": "I am grateful to be here, right now."}}'::jsonb),
  (12, 18, 'Je partage ma chaleur avec ceux que j’aime.', '{"en": {"text": "I share my warmth with the people I love."}}'::jsonb),
  (12, 19, 'Je me repose pendant les fêtes pour mieux repartir.', '{"en": {"text": "I rest over the holidays so I can set off again."}}'::jsonb),
  (12, 20, 'Mes rituels peuvent faire une pause, ma confiance reste.', '{"en": {"text": "My rituals can take a break; my confidence stays."}}'::jsonb),
  (12, 21, 'Après le jour le plus court, la lumière revient, et moi aussi.', '{"en": {"text": "After the shortest day, the light returns, and so do I."}}'::jsonb),
  (12, 22, 'Je ferme l’année en me pardonnant, et j’avance libre.', '{"en": {"text": "I close the year by forgiving myself, and I move on free."}}'::jsonb),
  (12, 23, 'J’aime mon corps tel qu’il est aujourd’hui.', '{"en": {"text": "I love my body as it is today."}}'::jsonb),
  (12, 24, 'La joie simple est ma plus grande richesse.', '{"en": {"text": "Simple joy is my greatest wealth."}}'::jsonb),
  (12, 25, 'Je donne avec générosité et je reçois avec gratitude.', '{"en": {"text": "I give generously and I receive with gratitude."}}'::jsonb),
  (12, 26, 'Je laisse cette année partir, fière de ce qu’elle m’a appris.', '{"en": {"text": "I let this year go, proud of what it taught me."}}'::jsonb),
  (12, 27, 'Je suis fière de chaque fois où j’ai choisi de revenir à moi.', '{"en": {"text": "I am proud of every time I chose to come back to myself."}}'::jsonb),
  (12, 28, 'Je fais le plein de calme avant de rêver à la suite.', '{"en": {"text": "I fill up on calm before dreaming of what comes next."}}'::jsonb),
  (12, 29, 'Je garde les leçons, je laisse les regrets.', '{"en": {"text": "I keep the lessons, I leave the regrets."}}'::jsonb),
  (12, 30, 'Je suis prête pour ce qui vient, et j’ai hâte.', '{"en": {"text": "I am ready for what is coming, and I can’t wait."}}'::jsonb),
  (12, 31, 'Merci, mon corps. Merci, ma tête. À nous l’année qui vient.', '{"en": {"text": "Thank you, my body. Thank you, my mind. Here’s to the year ahead."}}'::jsonb)
on conflict (month, day) do update
  set text = excluded.text, i18n = excluded.i18n, updated_at = now();
